name: Electron CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          # 修复 macOS 构建依赖
          if [ "$RUNNER_OS" == "macOS" ]; then
            npm install dmg-license@1.0.11 --no-save
          fi

      - name: Build Electron app
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"
        run: npm run electron:build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: |
            dist_electron/*.exe
            dist_electron/*.dmg
            dist_electron/*.AppImage
            !**/*.blockmap

      # Linux 系统特殊处理
      - name: Setup Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse libnss3 libgtk-3-0
