name: Electron CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        platform: [win, mac, linux]
        include:
          - platform: win
            os: windows-latest
            target: --win
            runs-on: windows-latest
            artifact-pattern: dist_electron/*.exe
          - platform: mac
            os: macos-latest
            target: --mac
            runs-on: macos-latest
            artifact-pattern: dist_electron/*.dmg
          - platform: linux
            os: ubuntu-latest
            target: --linux
            runs-on: ubuntu-latest
            artifact-pattern: dist_electron/*.AppImage

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          if [ "${{ matrix.platform }}" == "mac" ]; then
            npm install dmg-license@1.0.11 --no-package-lock
          fi

      - name: Build Electron app
        run: npm run electron:build ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: |
            ${{ matrix.artifact-pattern }}
            !**/*.blockmap

      # Linux 系统特殊处理
      - name: Setup Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse libnss3 libgtk-3-0
